# Generated by Django 4.2 on 2023-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
    ]
