# Generated by Django 4.2 on 2023-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_documentversion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
