# Generated by Django 4.2 on 2023-04-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_document_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uuid',
            field=models.UUIDField(default=123124235435546, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uuid',
            field=models.CharField(default=345805063, max_length=255, verbose_name='Идентификатор документа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
    ]
