# Generated by Django 4.2 on 2023-04-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_document_uuid_documentversion_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор документа'),
        ),
    ]
