# Generated by Django 4.2 on 2023-04-27 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_documentversion_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Идентификатор'),
        ),
    ]
